=== Sergey-Pashkov/homework_data_serialization/file_info_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
      "type": "object",
      "properties": {
          "file_name": { "type": "string" },
          "full_path": { "type": "string" },
          "file_size": { "type": "integer" },
          "creation_time": { "type": "string", "format": "date-time" },
          "last_modified": { "type": "string", "format": "date-time" }
      },
      "required": ["file_name", "full_path", "file_size", "creation_time", "last_modified"]
  }
}

=== Sergey-Pashkov/homework_data_serialization/project_root/output/file_info.json
[
    {
        "file_name": "file1_utf8_processed.txt",
        "full_path": "/Users/macbook/Яндекс.Диск/Visual Studio/homework_data_serialization/project_root/data/processed/file1_utf8_processed.txt",
        "file_size": 21,
        "creation_time": "2024-11-08 13:30:20",
        "last_modified": "2024-11-08 13:30:20"
    },
    {
        "file_name": "file3_utf8_processed.txt",
        "full_path": "/Users/macbook/Яндекс.Диск/Visual Studio/homework_data_serialization/project_root/data/processed/file3_utf8_processed.txt",
        "file_size": 13,
        "creation_time": "2024-11-08 13:30:20",
        "last_modified": "2024-11-08 13:30:20"
    },
    {
        "file_name": "file2_iso_processed.txt",
        "full_path": "/Users/macbook/Яндекс.Диск/Visual Studio/homework_data_serialization/project_root/data/processed/file2_iso_processed.txt",
        "file_size": 17,
        "creation_time": "2024-11-08 13:30:20",
        "last_modified": "2024-11-08 13:30:20"
    }
]
